### ISSUE TITLE
a few things don't look well in Internet Explorer

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#7] opened 2017-02-24 06:41 UTC
1st - logos in disclaimer page not arranged nicely. 
![image](https://cloud.githubusercontent.com/assets/8801702/23293065/0351accc-fab8-11e6-902f-3ec90871bb5c.png)

2 - legend for FC not resized to fit frame: 
![image](https://cloud.githubusercontent.com/assets/8801702/23293074/1c60c2d4-fab8-11e6-9772-1490f94cedcd.png)

3 - when loading a new layer (total veg cover) IE freezes and stops working. 
(it took long but loaded the second time I tried) 
![image](https://cloud.githubusercontent.com/assets/8801702/23293104/59edd2cc-fab8-11e6-8068-ea46c5fa5915.png)

**Comment by kring** [comment] 2017-03-09 02:39
1 is fixed by https://github.com/TerriaJS/geoglam-nm/pull/9.
2 is fixed by https://github.com/TerriaJS/terriajs/pull/2403
3 is caused by Internet Explorer taking a really long time to parse the ~800kB GetCapabilities response from the server, and completely blocking all updates while it is in progress.  I don't think there's anything we can do in TerriaJS to fix this, but it can be fixed by making the GetCapabilities response from the server smaller.  The vast majority of the GetCapabilities response is an enormous list of times.  This can be represented _much_ more compactly using `start/stop/period` notation rather than individual times, e.g. `2000-01-01T00:00:00.000Z/2009-12-31T21:00:00.000Z/PT3H`.

**Closed as completed** 2017-03-09 04:07 UTC
